// Generated by FlutterFire CLI. Run `flutterfire configure` to regenerate.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run `flutterfire configure` to generate firebase_options.dart.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbvUU12NXKUZqLSK3jc2eugQoZ_AcNcqA',
    appId: '1:36748270349:web:e42b73b443f73735e1ae44',
    messagingSenderId: '36748270349',
    projectId: 'myfinance-30c6c',
    authDomain: 'myfinance-30c6c.firebaseapp.com',
    storageBucket: 'myfinance-30c6c.firebasestorage.app',
    measurementId: 'G-GPN4EDWZ67',
  );

  // TODO: Run `flutterfire configure` to fill in real values.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD26IKZ0Vktr6aUmtTaFWeFzHTN97SYi1U',
    appId: '1:36748270349:android:0df94a3e17100675e1ae44',
    messagingSenderId: '36748270349',
    projectId: 'myfinance-30c6c',
    storageBucket: 'myfinance-30c6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHxadsSET71uSoNFDGkO_Ga1obAwnYBcA',
    appId: '1:36748270349:ios:e73dceb79a210859e1ae44',
    messagingSenderId: '36748270349',
    projectId: 'myfinance-30c6c',
    storageBucket: 'myfinance-30c6c.firebasestorage.app',
    iosBundleId: 'com.thobio.myFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TODO',
    appId: 'TODO',
    messagingSenderId: 'TODO',
    projectId: 'TODO',
    storageBucket: 'TODO',
    iosBundleId: 'TODO',
  );
}